### ISSUE TITLE
Предупреждение: Declaration of case-insensitive constants is deprecated

### ISSUE THREAD

**Issue by Suslik2004** [woxcab/vkrss#10]
Подскажите пожалуйста,все сделал по инструкции, вылезает ошибка

define(): Declaration of case-insensitive constants is deprecated
 Что можно сделать?

**Comment by woxcab** [comment]
Добрый день.

Это не ошибка, а пока лишь предупреждение (до выпуска PHP 8.0.0). Внесены правки. Прошу проверить, пропало ли предупреждение.

**Comment by Suslik2004** [comment]
Пропало, спасибо
