### ISSUE TITLE
Bug: post dates

### ISSUE THREAD

**Issue by Oreolek** [woxcab/vkrss#11]
Старые посты выскакивают в ленте заново, когда там появляются новые комментарии.

[ENG]: Old posts that get new comments appear as new posts in feed.

**Comment by woxcab** [comment]
Это скорее особенность конкретного агрегатора лент, который для определения уникальности записи учитывает счетчик комментариев. В самой RSS-ленте дата записи остается неизменной. Помимо этого каждая запись в RSS-ленте имеет GUID, который ваш агрегатор почему-то игнорирует.

**Comment by woxcab** [comment]
В качестве компромисса добавлен дополнительный параметр [` disable_comments_amount`](https://github.com/woxcab/vkrss#rus-comments-counter), который просто убирает счетчик комментариев из RSS-ленты.
