### ISSUE TITLE
Undefined property: stdClass::$description

### ISSUE THREAD

**Issue by eta-im** [woxcab/vkrss#12]
I get this error in vk2rss.php on row 527
I change this row:
                    case 'video': {
                        if (isset($attachment->video->restriction)) {
                            $video_text = $attachment->video->restriction->text;
                        } else {
-                            $video_text = $attachment->video->description;
                        }

                    case 'video': {
                        if (isset($attachment->video->restriction)) {
                            $video_text = $attachment->video->restriction->text;
                        } else {
+                            $video_text = isset($attachment->video->description) ? $attachment->video->description : '';
                        }

**Comment by woxcab** [comment]
Thank you for response. Please can you provide link to the wall post or video that produces this warning/error?

**Comment by eta-im** [comment]
> Thank you for response. Please can you provide link to the wall post or video that produces this warning/error?

I do not know, what post. It was for this group https://vk.com/fcks1942

**Comment by woxcab** [comment]
Thank you for information. Additional restriction checking is added.
