### ISSUE TITLE
VK Donut

### ISSUE THREAD

**Issue by zedzhen** [woxcab/vkrss#15]
Я подписан на VK Donut сообщества. Но в RSS нет сообщений оттуда.
Можно ли их получить?

**Comment by woxcab** [comment]
Добрый день.
Для генерации RSS используется именно [access token пользователя](https://github.com/woxcab/vkrss#rus-user-access-token), у которого оформлена подписка, а не сервисный ключ приложения?

**Comment by woxcab** [comment]
Проблема актуальна?

**Comment by zedzhen** [comment]
Да.
Я по этой инструкции ещё раз получил код. Я использую именно код из "access_token" "vk1.a.***"
Я проверил user_id в ответе, и по нему я действительно попадаю на свою страницу.
(Я создал пустое текстовое сообщество с 2 записями для всех и 2 для донов, в rss есть только общие)

**Comment by woxcab** [comment]
Можете привести пример сообщества, у которого на стене есть закрытые записи "только для подписчиков VK Donut"?

**Comment by zedzhen** [comment]
Вот созданное мной сообщество [public214769033](https://vk.com/public214769033).

**Comment by woxcab** [comment]
Да, похоже, по умолчанию метод [wall.get](https://vk.com/dev/wall.get) не возвращает записи для донов, хотя при этом в отликле уже давно реализовано [метаполе donut](https://vk.com/dev/objects/post) о том, является ли запись записью для донов. 

Но обнаружена незадокументированная возможность получения донатных постов, если дополнительно передать параметр `filter=donut`, т.е. обрабатывать эти записи отдельными от обычных записей запросами. Не вижу, есть ли возможность сразу объединить выдачи в один запрос с дефолтным `filter=all` (by owner and others). 

Не знаю, как лучше реализовать: 
* всегда по умолчанию делать запросы и к обычным записями, и к записям для донов (в этом случае запросы по донату могут быть пустышками — возвращать ничего, ошибку или еще что, например, при отсутствии подписки или отключенном VK Donut);
* или же ввести дополнительный параметр у скрипта —  что-то вроде `donut`, сигнализирующий о необходимости запросов записей для донов.

Склоняюсь ко второму варианту со значением по умолчанию `false`. Единственное, порядок записей в RSS-ленте будет такой: сначала обычные записи, потом донатные (или можно наоборот), в силу последовательности обработки отдельных запросов, но все даты будут корректными, т.е. в случае собственной сортировки у RSS клиентов (кроме "по дате импортирования") порядок записей в RSS-ленте не должен иметь значения.

**Comment by woxcab** [comment]
Добавлен новый GET-параметр `donut`, который можно включать только при наличии ключа доступа пользователя, у которого есть VK Donut подписка у сообщества с указанным `id`. Немного подробнее тут: https://github.com/woxcab/vkrss#rus-donut

Прошу проверить функциональность в ваших ситуациях.

**Comment by zedzhen** [comment]
Да, всё работает.
