### ISSUE TITLE
👋. Как спарсить страницы вида:https://vk.com/video/@quality_journal ?

### ISSUE THREAD

**Issue by ozonar** [woxcab/vkrss#18]

**Comment by woxcab** [comment]
Этому посвящены методы API раздела Video:
https://dev.vk.com/ru/method/video
В частности, метод [video.get](https://dev.vk.com/ru/method/video.get) выводит список видеозаписей пользователя или сообщества. Для вашего примера запрос выглядит так:
`https://api.vk.com/method/video.get?v=5.199&access_token=ACCESS_TOKEN&owner_id=-68670236`
Числовой идентификатор (owner_id) можно узнать по любому видео из списка видео пользователя/сообщества — это первое число в ссылке (в случае сообщества оно начинается со знака минус).
