### ISSUE TITLE
Подтягивается мобильная версия

### ISSUE THREAD

**Issue by cema93** [woxcab/vkrss#4]
Добрый день!
Использую плагин для wordpress  чтобы получать rss ленту из ВК.
У меня почему-то подтягиваются ссылки на мобильные версии контакта.
Можно ли как-то реализовать, чтобы ссылки всегда были на десктопную версию?

**Comment by woxcab** [comment]
Добрый день.
Какие именно (в какой части RSS item) ссылки ведут на мобильную версию? Желательно приложить RSS ленту или ее фрагмент, иллюстрирующий проблему, а также при необходимости ссылку на пост Вконтакте, если дело касается его содержания.

**Comment by cema93** [comment]
В полях 
<link>https://vk.com/wall-118476917_559</link>
или
<guid>https://vk.com/wall-118476917_559</guid>

**Comment by cema93** [comment]
item link или guid

**Comment by woxcab** [comment]
`guid` и `link` всегда ссылают на домен `vk.com`, а не на `m.vk.com`. Уверены, что вас сам Вконтакте просто не перенаправляет на мобильную версию уже после перехода по ссылке?
Лучше приложите кусок RSS ленты с этой проблемой, если в ней действительно есть домен `m.vk.com`.

**Comment by cema93** [comment]
увы, я не могу увидеть ленту, которую получает плагин, который дальше её обрабатывает.
Если вы уверены, что  в ленте не может быть ссылок на мобильную версию,  тогда вопрос с нят.

**Comment by woxcab** [comment]
Вот строчка кода, отвечающая за ссылку в `link`: 
https://github.com/woxcab/vkrss/blob/6b85a05db306cf4291ee3f9d6ba10ae8d41ef096/Vk2rss.php#L215
и за ссылку в `guid`
https://github.com/woxcab/vkrss/blob/6b85a05db306cf4291ee3f9d6ba10ae8d41ef096/Vk2rss.php#L216
Как видно, они всегда начинаются с https://vk.com/, в то время как для мобильной версии ссылки начинаются с `https://m.vk.com/`.
Так что есть подозрения считать, что кто-то уже после получения ссылок из RSS ленты перенаправляет на мобильную версию.

**Comment by cema93** [comment]
Судя по всему да :( спасибо 👍
