### ISSUE TITLE
Репост в группе

### ISSUE THREAD

**Issue by cema93** [woxcab/vkrss#6]
Добрый день!
подтягиваю рсс из групп, но никак не отмечается, что это репост и нет ссылки на оригинал.
Это верное поведение?
Можно ли добавить ссылку на группу или ивент с которого сделан репост?

**Comment by woxcab** [comment]
Добрый день.
В терминах RSS как Вы представляете такое?
Сейчас по этому поводу максимум, что есть, — указание у каждой записи авторства изначального поста (элемент `author`). Т.е. если автор (человек/сообщество) записи не совпадает с владельцем стены, то это говорит о том, что эта запись — репост.

**Comment by cema93** [comment]
в каком-то плагине видел, что делали так:
был написан текст, который нписал автор группы, которую я в рсс добавил, а нижело написано
`название группы:` со ссылкой на эту группу
и дальше текст поста, который репостнули.

Возможно это не всем надо, но может кому-то будет удобно

**Comment by woxcab** [comment]
Т.е. текущего указания в `author` автора исходного поста недостаточно?

**Comment by cema93** [comment]
увы, не достаточно :( не во всех ридерах обрабатывается поле автор

**Comment by woxcab** [comment]
Возможно, можно реализовать так: вместо фиксированного разделителя родительских и дочерних записей сделать возможность выбора второго типа разделителя, при котором указывается автор дочерней записи.
Но вообще элемент `author` является одним из основных элементов в RSS item, так что странно, что его кто-то не поддерживает.

**Comment by cema93** [comment]
> вместо фиксированного разделителя родительских и дочерних записей сделать возможность выбора второго типа разделителя

Думаю, что это было бы идеально :)

**Comment by woxcab** [comment]
Описание нового параметра:
https://github.com/woxcab/vkrss#rus-repost-delimiter
